import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { useState } from 'react'
import Hero from '../components/Hero';
import Skills from '../components/Skills';
import ThreeComp from '../components/ThreeComp'
import { motion } from 'framer-motion';
import About from '../components/About';
import WorkExp from '../components/WorkExp';
import { AiOutlineMenu } from "react-icons/ai";
import Projects from '../components/Projects';
import { Dropdown, Menu } from 'antd';
import { menu } from '../components/MenuData';


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? 'dark' : ""}>

      <Head>
        <title>Payal Khandelwal Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ToastContainer autoClose={1500}/>

      <main className='dark:bg-red-400 bg-gradient-to-br from-pink-500 to-yellow-300 px-10 dark:from-[#5C258D] dark:to-[#4389A2] md:px-20 lg:px-40 pb-20 h-screen snap-y snap-mandatory overflow-scroll scrollbar-track-inherit scrollbar-thumb-white scrollbar-thin'>

          <nav className='py-10 mb-12 flex justify-between sticky top-0 z-20'>
            <motion.div
              initial={{
                x: -500,
                opacity: 0,
                scale: 0.5,
              }}
              animate={{
                x:0,
                opacity: 1,
                scale: 1
              }}
              transition={{
                duration: 1.5
              }}
            >
              <div>
                <Dropdown overlay={menu}>
                  <button><AiOutlineMenu color='white'/></button>
                </Dropdown>
              </div>
            </motion.div>
            <motion.div
              initial={{
                x: 500,
                opacity: 0,
                scale: 0.5,
              }}
              animate={{
                x:0,
                opacity: 1,
                scale: 1
              }}
              transition={{
                duration: 1.5
              }}
            >
              <ul className='flex items-center'>
                <li><BsFillMoonStarsFill color={darkMode ? 'white' : 'black'} onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl'/></li>
                <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 hover:text-gray-700 text-white px-4 py-2 rounded-md ml-8' href='/resume.pdf' target = "_blank">Resume</a></li>
              </ul>
            </motion.div>
          </nav>

          <section id='hero' className='pt-32 min-h-screen snap-start'>
            <Hero />
            <motion.div
            initial={{ opacity: 0}}
            whileInView={{opacity: 1}}
            transition={{duration: 2}}
            >
              <ThreeComp />
            </motion.div>
          </section>

        <section id='about' className='snap-center'>
          <About />
        </section>

        <section id='skills' className='snap-center'>
          <Skills />
        </section>

        <section id='workexp' className='snap-center'>
          <WorkExp />
        </section>

        <section id='projects' className='snap-center'>
          <Projects />
        </section>

      </main>
    </div>
  )
}
